export interface TransferIn {
    transferInId: number
    folioNo: string,
    schemeId: number,
    schemeCode: string,
    investmentType: string,
    schemeName: string,
    currentAmount: number,
    sipAllowedDate: string[],
    isEnachEnable: boolean,
    isBillerEnable: boolean,
    sipDate: string,
    minAmount: number,
    sipAllowed: boolean,
    lumpSumAllowed: boolean,
    isipAllowed: boolean,
    sipAmount: number
}

export interface TransferInResp {
    transferInId: number,
    folioNo: string,
    schemeName: string,
    sipAmount: number,
    schemeCode: string,
    enachEnable: boolean,
    billerEnable: boolean,
    sipAllowedDate: string[],
    maxSipAmount: number,
    maxLumpsumAmount: number,
    sipDate: string,
    investmentType: string,
    minSipAmount: number,
    minLumpsumAmount: number,
    investedAmount: number,
    availableUnit: number,
    amcCode: string,
    currentNav: number,
    schemeType: string,
    allotedUnit: number,
    goalName: string,
    goalId: number,
    isRedemptionAllowed: string,
    startedOn: string,
    minimumRedemptionAmount: number,
    sipAllowed: boolean,
    isipAllowed: boolean,
    minAdditionalAmount: number,
    lumpsumAllowed: boolean
}